services:
  backend:
    build:
      context: .
    image: django_test:latest
    container_name: django_test_app
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "3100:8000"
    networks:
      - backnet
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file: 
      - .env

  db:
    image: postgres
    container_name: django_test_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    ports:
      - 5432:5432
    networks:
      - backnet
    # secrets:
    #   - db-password
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env

  redis:
    image: redis
    container_name: django_test_redis
    ports:
      - 6379:6379
    networks:
      - backnet

  pgadmin_container:
    image: dpage/pgadmin4:latest
    container_name: django_test_pgadmin
    restart: always
    ports:
      - 5050:80
    networks:
      - backnet
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db_data:
  pgadmin_data:

networks:
  backnet:
    