# Generated by Django 5.0.4 on 2024-04-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date',
            field=models.DateField(default='2024-04-04'),
            preserve_default=False,
        ),
    ]
