# Generated by Django 5.0.4 on 2024-04-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movies_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='clasificacion',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
