# Generated by Django 5.0.4 on 2024-04-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='create_uid_movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_uid_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movies',
            name='write_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='write_uid_movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_uid_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='create_uid_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_uid_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='write_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='write_uid_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_uid_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=10, verbose_name='Classification name')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_uid_classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_uid_classification', to=settings.AUTH_USER_MODEL)),
                ('write_uid_classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_uid_classification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='clasificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.classification'),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_uid_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_uid_director', to=settings.AUTH_USER_MODEL)),
                ('write_uid_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_uid_director', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='directors',
            field=models.ManyToManyField(to='movie.director'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Genre of the movie', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_uid_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_uid_genre', to=settings.AUTH_USER_MODEL)),
                ('write_uid_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_uid_genre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
