# Generated by Django 5.0.4 on 2024-04-09 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movies_create_date_movies_create_uid_movies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='movies',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(choices=[('A', 'Classification A'), ('B', 'Classification B'), ('C', 'Classification C')], max_length=2, verbose_name='Classification name'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.DateField(verbose_name='Fecha de Estreno'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='write_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['-create_date'], name='movie_movie_create__b722d9_idx'),
        ),
    ]
